version: 2.1

orbs:
  build-tools: circleci/build-tools@volatile

jobs:
  validate:
    executor: build-tools/ci-base
    steps:
      - run: npm install -g swagger-cli
      - run: swagger-cli validate v2.  

workflows:
  main:
    jobs:
      - validate