openapi: "3.0.0"
info:
  version: 1.0.0
  title: CircleCI API v2
  license:
    name: MIT
servers:
  - url: http://circleci.com/api/v2
paths:
  /me:
    get:
      summary: Return basic user information of the owner of the requested token
      operationId: me
      responses:
        '200':
          description: A map of simple user information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Actor"
  /workflow/{id}:
    get:
      summary: Return summary fields of a workflow by ID
      operationId: GET workflow by ID
      parameters:
        - name: id
          in: path
          description: ID of the workflow
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: An object with workflow information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Workflow"
  /workflow/{id}/jobs:
    get:
      summary: Return all the known jobs of a given workflow
      operationId: GET workflow jobs by ID
      parameters:
        - name: id
          in: path
          description: ID of the workflow
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: a paginated set of a workflow's jobs as an inverted adjacency list
          content:
            application/json:
              schema:
                type: object
                properties:
                  next_page_token:
                    type: string
                  jobs:
                    type: array
                    items:
                      $ref: "#/components/schemas/Job"
components:
  schemas:
    Actor:
      type: object
      properties:
        login:
          type: string
        name:
          type: string
    Workflow:
      type: object
    Job:
      type: object
      required:
        - id
        - name
        - type
        - status
        - start_time
        - dependencies
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        type:
          type: string
          enum: ["build", "approval"]
        status:
          type: string
          enum: ["queued", "running", "success", "failed"]
        start_time:
          type: string
          format: dateTime
        # NB stop_time is not required
        stop_time:
          type: string
          format: dateTime
        dependencies:
          type: array
          items:
            type: string
            format: uuid
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
